apiVersion: 1

groups:
  - orgId: 1
    name: biblioteca-http-errors
    folder: Biblioteca Alerting
    interval: 10s
    rules:
      - uid: biblioteca-http-500
        title: Troppi errori HTTP 500
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: sum(increase(http_server_requests_seconds_count{job="biblioteca", status="500"}[1m]))
              instant: true
              intervalMs: 15000
              legendFormat: Errori HTTP 500
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              type: reduce
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 10
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        dashboardUid: biblioteca-jvm
        panelId: 8
        noDataState: OK
        execErrState: Error
        for: 0s
        annotations:
          __dashboardUid__: biblioteca-jvm
          __panelId__: "8"
          description: Più di 10 risposte HTTP 500 sono state registrate nell'ultimo minuto.
          summary: Soglia critica degli errori HTTP 500 superata.
        labels:
          service: biblioteca
          severity: critical
        isPaused: false
